# Use Node.js 18 as the base image
FROM node:18

# Set working directory
WORKDIR /app

# Install dependencies
COPY /web/services/chat/package*.json ./
RUN npm install

# Copy the rest of the server code
COPY /web/services/chat ./