# Use official Node.js image for server
FROM node:18

# Set working directory
WORKDIR /app/client

# Install dependencies
COPY web/server/package*.json ./

RUN npm install

COPY web/server ./

# Expose the port the server will run on
EXPOSE 3333

# Command to run Prisma migrations and start the server using nodemon
CMD ["npm", "run", "dev"]
