# Dockerfile.client
# Use official Node.js image for the client
FROM node:18

# Set working directory
WORKDIR /app

# Install dependencies
COPY web/client/package.json .

RUN npm install

# Copy all files to the container
COPY web/client .

EXPOSE 3003

# Run development server with hot-reloading for client
CMD ["npm", "run", "dev"]
