services:
    postgres:
        image: postgres:15-alpine
        container_name: apex_care_db
        environment:
            POSTGRES_USER: apex_admin
            POSTGRES_PASSWORD: apex_admin
            POSTGRES_DB: apex_care_db
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    server:
        build:
            context: .
            dockerfile: Dockerfile.server
        volumes:
            - ./web/server:/app
            - server_node_modules:/app/node_modules
        ports:
            - "3333:3333"
        environment:
            NODE_ENV: development
            DATABASE_URL: postgres://apex_admin:apex_admin@postgres:5432/apex_care_db
        depends_on:
            - postgres
        command: >
            sh -c "npx prisma migrate dev && npx nodemon --watch src --exec npm start"

    client:
        build:
            context: .
            dockerfile: Dockerfile.client
        ports:
            - "3003:3003"
        volumes:
            - ./web/client:/app
            - client_node_modules:/app/node_modules
        environment:
            NODE_ENV: development

volumes:
    postgres_data:
    server_node_modules:
    client_node_modules:
