services:
    postgres:
        image: postgres:15-alpine
        container_name: apex_care_db
        environment:
            POSTGRES_USER: apex_admin
            POSTGRES_PASSWORD: apex_admin
            POSTGRES_DB: apex_care_db
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        restart: always

    server:
        build:
            context: .
            dockerfile: Dockerfile.server
        depends_on:
            - postgres
        ports:
            - "3333:3333"
        environment:
            NODE_ENV: development
            DATABASE_URL: postgres://apex_admin:apex_admin@postgres:5432/apex_care_db
            PORT: 3333
            HOST: 0.0.0.0
        restart: always
        volumes:
            - ./web/server:/app
            - /app/node_modules
        command: >
            sh -c "npx prisma generate && npx prisma migrate deploy && npm run dev"
        env_file:
            - ./web/server/.env

volumes:
    postgres_data:
