services:
    postgres:
        image: postgres:15-alpine
        container_name: apex_care_db
        environment:
            POSTGRES_USER: apex_admin
            POSTGRES_PASSWORD: apex_admin
            POSTGRES_DB: apex_care_db
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        restart: always

    app:
        build:
            context: .
            dockerfile: Dockerfile.app
        depends_on:
            - postgres
        ports:
            - "3000:3000"
            - "5555:5555"
        environment:
            NODE_ENV: development
            DATABASE_URL: postgres://apex_admin:apex_admin@postgres:5432/apex_care_db
            PORT: 3000
            HOST: 0.0.0.0
        restart: always
        volumes:
            - ./web/app:/app
            - /app/node_modules
        command: >
            sh -c "npx prisma generate && npx prisma migrate deploy && npm run dev"
        env_file:
            - ./web/app/.env

    service-chat:
        build:
            context: .
            dockerfile: Dockerfile.service.chat
        depends_on:
            - postgres
        ports:
            - "3333:3333"
        environment:
            NODE_ENV: development
            APEX_CARE_API_BASE_URL: http://app:3000
            PORT: 3333
            HOST: 0.0.0.0
        restart: always
        volumes:
            - ./web/services/chat:/app
            - /app/node_modules
        command: npm run dev
        env_file:
            - ./web/services/chat/.env

volumes:
    postgres_data:
